

// Codes pays — Niger en premier, puis ordre alphabétique
export const COUNTRY_CODES = [
    { code: '227', name: 'Niger',                flag: '🇳🇪' },
    { code: '213', name: 'Algerie',              flag: '🇩🇿' },
    { code: '244', name: 'Angola',               flag: '🇦🇴' },
    { code: '229', name: 'Benin',                flag: '🇧🇯' },
    { code: '267', name: 'Botswana',             flag: '🇧🇼' },
    { code: '226', name: 'Burkina Faso',         flag: '🇧🇫' },
    { code: '257', name: 'Burundi',              flag: '🇧🇮' },
    { code: '238', name: 'Cap-Vert',             flag: '🇨🇻' },
    { code: '237', name: 'Cameroun',             flag: '🇨🇲' },
    { code: '236', name: 'Centrafrique',         flag: '🇨🇫' },
    { code: '269', name: 'Comores',              flag: '🇰🇲' },
    { code: '242', name: 'Congo',                flag: '🇨🇬' },
    { code: '243', name: 'Congo (RDC)',          flag: '🇨🇩' },
    { code: '253', name: 'Djibouti',             flag: '🇩🇯' },
    { code: '20',  name: 'Egypte',              flag: '🇪🇬' },
    { code: '240', name: 'Guinee equatoriale',   flag: '🇬🇶' },
    { code: '291', name: 'Erythree',             flag: '🇪🇷' },
    { code: '251', name: 'Ethiopie',             flag: '🇪🇹' },
    { code: '241', name: 'Gabon',                flag: '🇬🇦' },
    { code: '220', name: 'Gambie',               flag: '🇬🇲' },
    { code: '233', name: 'Ghana',                flag: '🇬🇭' },
    { code: '224', name: 'Guinee',               flag: '🇬🇳' },
    { code: '245', name: 'Guinee-Bissau',        flag: '🇬🇼' },
    { code: '225', name: 'Cote d\'Ivoire',       flag: '🇨🇮' },
    { code: '254', name: 'Kenya',                flag: '🇰🇪' },
    { code: '266', name: 'Lesotho',              flag: '🇱🇸' },
    { code: '231', name: 'Liberia',              flag: '🇱🇷' },
    { code: '218', name: 'Libye',                flag: '🇱🇾' },
    { code: '261', name: 'Madagascar',           flag: '🇲🇬' },
    { code: '265', name: 'Malawi',               flag: '🇲🇼' },
    { code: '223', name: 'Mali',                 flag: '🇲🇱' },
    { code: '222', name: 'Mauritanie',           flag: '🇲🇷' },
    { code: '230', name: 'Maurice',              flag: '🇲🇺' },
    { code: '212', name: 'Maroc',               flag: '🇲🇦' },
    { code: '258', name: 'Mozambique',           flag: '🇲🇿' },
    { code: '264', name: 'Namibie',              flag: '🇳🇦' },
    { code: '234', name: 'Nigeria',              flag: '🇳🇬' },
    { code: '250', name: 'Rwanda',               flag: '🇷🇼' },
    { code: '239', name: 'Sao Tome-et-Principe', flag: '🇸🇹' },
    { code: '221', name: 'Senegal',              flag: '🇸🇳' },
    { code: '232', name: 'Sierra Leone',         flag: '🇸🇱' },
    { code: '252', name: 'Somalie',              flag: '🇸🇴' },
    { code: '27',  name: 'Afrique du Sud',       flag: '🇿🇦' },
    { code: '211', name: 'Soudan du Sud',        flag: '🇸🇸' },
    { code: '249', name: 'Soudan',               flag: '🇸🇩' },
    { code: '268', name: 'Eswatini',             flag: '🇸🇿' },
    { code: '255', name: 'Tanzanie',             flag: '🇹🇿' },
    { code: '228', name: 'Togo',                 flag: '🇹🇬' },
    { code: '216', name: 'Tunisie',              flag: '🇹🇳' },
    { code: '256', name: 'Ouganda',              flag: '🇺🇬' },
    { code: '260', name: 'Zambie',               flag: '🇿🇲' },
    { code: '263', name: 'Zimbabwe',             flag: '🇿🇼' },
    // Europe
    { code: '33',  name: 'France',               flag: '🇫🇷' },
    { code: '32',  name: 'Belgique',             flag: '🇧🇪' },
    { code: '41',  name: 'Suisse',               flag: '🇨🇭' },
    { code: '352', name: 'Luxembourg',           flag: '🇱🇺' },
    { code: '1',   name: 'USA / Canada',         flag: '🇺🇸' },
    { code: '44',  name: 'Royaume-Uni',          flag: '🇬🇧' },
    { code: '49',  name: 'Allemagne',            flag: '🇩🇪' },
    { code: '34',  name: 'Espagne',              flag: '🇪🇸' },
    { code: '39',  name: 'Italie',               flag: '🇮🇹' },
    { code: '351', name: 'Portugal',             flag: '🇵🇹' },
    // Moyen-Orient
    { code: '966', name: 'Arabie saoudite',      flag: '🇸🇦' },
    { code: '971', name: 'Emirats arabes unis',  flag: '🇦🇪' },
    { code: '974', name: 'Qatar',                flag: '🇶🇦' },
    // Asie
    { code: '91',  name: 'Inde',                 flag: '🇮🇳' },
    { code: '86',  name: 'Chine',                flag: '🇨🇳' },
];